import { CakeProduct, DeliveryZone, Flavor, PaymentMethod } from "@/types";

export const siteConfig = {
  name: "Pâtisserie Docteur Cakes",
  shortName: "Docteur Cakes",
  tagline: "Créateur de gâteaux d'anniversaire, wedding cakes et douceurs personnalisées à Cocody",
  description: "Pâtisserie fine & Cake Design sur mesure à Abidjan (Cocody). Gâteaux d'anniversaire, wedding cakes prestige, gâteaux de dot traditionnelle et mignardises salées.",
  url: "https://docteurcakes-v2-website.vercel.app",
  author: "Pâtisserie Docteur Cakes",
  
  contact: {
    phonePrimary: "+225 07 49 91 13 90",
    phoneSecondary: "+225 07 89 90 62 93",
    phoneRaw: "2250749911390",
    email: "docteurcakes73@gmail.com",
    address: {
      street: "Rue G30, n°188",
      neighborhood: "Cocody",
      city: "Abidjan",
      country: "Côte d'Ivoire",
      full: "Rue G30, n°188, Cocody, Abidjan, Côte d'Ivoire",
    },
    hours: "Mardi au Dimanche : 08h30 – 19h00 (Lundi sur rendez-vous)",
  },

  social: {
    facebook: "https://facebook.com/DocteurCakes",
    whatsappCatalog: "https://wa.me/c/22549911390",
    facebookFollowers: "57 000+",
  },

  pricingBase: {
    cremePerPortion: 3500,
    cremeMinPortions: 5,
    cremeMinPrice: 17500,
    pateSucrePerPortion: 4000,
    pateSucreMinPortions: 10,
    pateSucreMinPrice: 40000,
    weddingPerPortionMin: 4000,
    weddingPerPortionMax: 8000,
  },

  flavors: [
    { name: "Fruits Rouges", notes: "Couli acidulé & morceaux de framboises et myrtilles" },
    { name: "Cerelac Douceur", notes: "Saveur d'enfance réconfortante et crème onctueuse" },
    { name: "Caramel Beurre Salé", notes: "Caramel ambré cuit maison à la fleur de sel" },
    { name: "Chocolat Noir Intense", notes: "Ganache pure origine riche et corsée" },
    { name: "Vanille Bourbon", notes: "Gousses de Madagascar infusées à froid" },
    { name: "Oreo Gourmand", notes: "Brisures de biscuits craquants & crème lactée" },
    { name: "Spéculoos Croustillant", notes: "Épices douces de cannelle et croquant caramélisé" },
    { name: "Bailey's Cream", notes: "Note subtile de crème d'Irlande (réservé aux adultes)" },
    { name: "Citron Meringué", notes: "Crémeux citron jaune frais et zeste vivifiant" },
    { name: "Menthe Fraîche", notes: "Infusion de feuilles de menthe du potager" },
    { name: "Moka Café", notes: "Arabica torréfié et ganache moka soyeuse" },
    { name: "Pomme Caramélisée", notes: "Compotée de pommes dorées à la cannelle" },
    { name: "Toffee Muscade", notes: "Crème toffee onctueuse rehaussée d'une touche de muscade" },
    { name: "Fraise des Bois", notes: "Selon arrivage de saison", seasonal: true },
  ] as Flavor[],

  deliveryZones: [
    { name: "Cocody (Zone Atelier)", price: 15000, delay: "Livraison dédiée avec chauffeur climatisé" },
    { name: "Abidjan (Hors Cocody : Plateau, Marcory, Zone 4, Yopougon...)", price: 25000, delay: "Livraison sécurisée sous caisse isotherme" },
    { name: "Intérieur de la Côte d'Ivoire (Bassam, Yamoussoukro, Bouaké...)", price: 40000, delay: "Transport spécial longue distance" },
  ] as DeliveryZone[],

  paymentMethods: [
    { name: "Wave", phone: "+225 07 49 91 13 90", instructions: "Paiement direct Wave sans frais" },
    { name: "MTN Mobile Money", phone: "+225 05 84 22 49 49", instructions: "Compte marchand officiel" },
    { name: "Orange Money", phone: "+225 07 89 90 62 93", instructions: "Validation instantanée" },
  ] as PaymentMethod[],

  products: [
    {
      id: "wedding-royal-4-etages",
      name: "Wedding Cake Royal 4 Étages",
      category: "mariage",
      price: 600000,
      priceNote: "Pour 120 à 150 convives",
      portions: 120,
      description: "Pièce montée monumentale ornée de roses terracotta, bleu nuit et crème avec médaillon hexagonal doré Mr & Mrs.",
      image: "/images/cakes/wedding-cake-royal-4-etages.jpg",
      badge: "Prestige Haute Couture",
      highlights: ["Structure 4 étages consolidée", "Fleurs stabilisées faites main", "Socle doré inclus"],
      isFeatured: true,
    },
    {
      id: "wedding-floral-3-etages",
      name: "Wedding Cake Floral 3 Étages",
      category: "mariage",
      price: 180000,
      priceNote: "Environ 45 à 50 parts",
      portions: 45,
      description: "Texture striée à la crème, bordures perlées et cascade florale pêche et ivoire avec topper anneaux dorés.",
      image: "/images/cakes/wedding-cake-floral-3-etages.jpg",
      badge: "Incontournable Mariage",
      highlights: ["Glaçage crème soyeux", "Finition perles d'eau douce", "Topper acrylique doré"],
      isFeatured: true,
    },
    {
      id: "wedding-perle-love",
      name: "Wedding Cake Perlé 'LOVE'",
      category: "mariage",
      price: 200000,
      priceNote: "Environ 50 parts",
      portions: 50,
      description: "Élégance 3 étages en blanc perlé, cascade de roses orange pastel et médaillon cœur doré 'LOVE'.",
      image: "/images/cakes/wedding-cake-perle-love.jpg",
      badge: "Coup de Cœur",
      highlights: ["Médaillon cœur doré", "Bouquet pastel", "Texture velours nacrée"],
      isFeatured: true,
    },
    {
      id: "dot-baoule-wax",
      name: "Gâteau de Dot Baoulé Wax Indigo",
      category: "dot",
      price: 90000,
      priceNote: "20 à 25 parts",
      portions: 22,
      description: "Gâteau traditionnel 2 étages orné de motifs géométriques Baoulé imprimés sur pâte à sucre et losanges dorés.",
      image: "/images/cakes/gateau-dot-baoule-wax.jpg",
      badge: "Mariage Coutumier",
      highlights: ["Tissu Baoulé en sucre", "Plaque personnalisée Mr & Mrs", "Détails or pur"],
      isFeatured: true,
    },
    {
      id: "dot-libation-akan",
      name: "Gâteau de Dot Libation Akan",
      category: "dot",
      price: 100000,
      priceNote: "25 parts",
      portions: 25,
      description: "Création hommage aux traditions avec bouteille de gin sculptée en sucre et pièces d'or comestibles.",
      image: "/images/cakes/gateau-dot-libation-akan.jpg",
      badge: "Cérémonie Traditionnelle",
      highlights: ["Bouteille en pâte à sucre", "Pièces d'or Akan", "Symbolique de la dot"],
      isFeatured: true,
    },
    {
      id: "anniversaire-marbre-bleu",
      name: "Gâteau Marbré Bleu Roi & Or",
      category: "anniversaire",
      price: 45000,
      priceNote: "12 parts généreuses",
      portions: 12,
      description: "Effet marbré volutes bleu royal, turquoise et feuilles d'or 24 carats avec grappe de perles dorées.",
      image: "/images/cakes/gateau-anniversaire-marbre-bleu-or.jpg",
      badge: "Signature Anniversaire",
      highlights: ["Marbrage artisanal", "Feuilles d'or comestibles", "Perles croquantes"],
      isFeatured: true,
    },
    {
      id: "anniversaire-hello-30",
      name: "Gâteau Prestige 'Hello 30' Or & Blanc",
      category: "anniversaire",
      price: 35000,
      priceNote: "10 parts",
      portions: 10,
      description: "Lissage blanc pur, dorure en relief, 6 bougies torsadées dorées et topper géométrique Joyeux Anniversaire.",
      image: "/images/cakes/gateau-anniversaire-hello-30-or.jpg",
      badge: "Célébration",
      highlights: ["Lissage haute précision", "Bougies dorées offertes", "Personnalisation d'âge"],
      isFeatured: true,
    },
    {
      id: "bapteme-saint-esprit",
      name: "Gâteau Baptême & Communion Saint-Esprit",
      category: "bapteme",
      price: 100000,
      priceNote: "25 parts (2 étages)",
      portions: 25,
      description: "2 étages blanc immaculé, font baptismal, colombe dorée du Saint-Esprit et chapelet en perles de sucre.",
      image: "/images/cakes/gateau-bapteme-saint-esprit.jpg",
      badge: "Sacrement & Bénédiction",
      highlights: ["Colombe sculptée", "Chapelet doré", "Drapé satin en fondant"],
      isFeatured: true,
    },
    {
      id: "anniversaire-bebe-elior",
      name: "Gâteau Enfant 'Ourson Céleste'",
      category: "enfants",
      price: 45000,
      priceNote: "12 parts",
      portions: 12,
      description: "Ourson modelé à la main tenant ses ballons bleus, cookies chocolatés en sucre et sphères dorées.",
      image: "/images/cakes/gateau-anniversaire-bebe-elior.jpg",
      badge: "Naissance & 1er Âge",
      highlights: ["Figurine ourson modelée", "Ballons aériens", "Biscuits décoratifs"],
      isFeatured: true,
    },
    {
      id: "signature-creme-fleurs",
      name: "Pavé Signature Crème & Pétales Roses",
      category: "anniversaire",
      price: 55000,
      priceNote: "15 parts",
      portions: 15,
      description: "Design rectangulaire couture à texture plissée en papier azyme, fines bougies dorées ondulées et fleurs fraîches.",
      image: "/images/cakes/gateau-signature-creme-fleurs.jpg",
      badge: "Création Atelier",
      highlights: ["Texture plissée couture", "Fleurs délicates", "Bougies ondulées"],
      isFeatured: true,
    },
    {
      id: "plateau-apero-froids",
      name: "Plateau Apéro Froids Prestige",
      category: "mignardises",
      price: 30000,
      priceNote: "Assortiment 20 pièces",
      portions: 20,
      description: "Canapés sur baguette fraîche : crème & caviar avec tomate cerise, chiffonnade de jambon et saucisson gourmet.",
      image: "/images/cakes/plateau-apero-froids.jpg",
      badge: "Traiteur Salé",
      highlights: ["Ingrédients frais du jour", "Présentation soignée", "Idéal cocktail"],
      isFeatured: true,
    },
    {
      id: "plateau-affro-gourmet",
      name: "Plateau Affro Gourmand",
      category: "mignardises",
      price: 35000,
      priceNote: "Assortiment complet 25 pièces",
      portions: 25,
      description: "Pastels dorés garnis de viande hachée épicée, mini-bruschettas au poulet émincé, roulés wraps et mini-burgers.",
      image: "/images/cakes/plateau-affro-gourmet.jpg",
      badge: "Cocktail Réception",
      highlights: ["Pastels croustillants", "Mini-burgers dorés", "Sauce piment douce incluse"],
      isFeatured: true,
    },
  ] as CakeProduct[],
};
